apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem          
  resources:
    requests:
      storage: 20Gi
  storageClassName: jenkins-pv
  #selector:
  #  matchLabels:
  #    app: jenkins-pv
