apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  #type: NodePort
  externalIPs:
    - 54.244.111.22
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: jenkins
